---
- name: install python bindings for SELinux
  yum:
    name: ["libselinux-python", "libsemanage-python"]
    state: present

- name: test to see if SeLinux is running
  command: getenforce
  register: sestatus # Save the response of the command
  changed_when: false
